In [1]:
import pandas as pd
import numpy as np

# Understanding the Data

In [3]:
df = pd.read_csv('../data/raw_data/diabetic_data.csv')

In [5]:
print("Shape", df.shape)
df.head()

Shape (101766, 50)

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),?,6,25,1,1,...,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),?,1,1,7,3,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),?,1,1,7,2,...,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),?,1,1,7,2,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),?,1,1,7,1,...,No,Steady,No,No,No,No,No,Ch,Yes,NO

In [6]:
df.columns.tolist()

['encounter_id',
 'patient_nbr',
 'race',
 'gender',
 'age',
 'weight',
 'admission_type_id',
 'discharge_disposition_id',
 'admission_source_id',
 'time_in_hospital',
 'payer_code',
 'medical_specialty',
 'num_lab_procedures',
 'num_procedures',
 'num_medications',
 'number_outpatient',
 'number_emergency',
 'number_inpatient',
 'diag_1',
 'diag_2',
 'diag_3',
 'number_diagnoses',
 'max_glu_serum',
 'A1Cresult',
 'metformin',
 'repaglinide',
 'nateglinide',
 'chlorpropamide',
 'glimepiride',
 'acetohexamide',
 'glipizide',
 'glyburide',
 'tolbutamide',
 'pioglitazone',
 'rosiglitazone',
 'acarbose',
 'miglitol',
 'troglitazone',
 'tolazamide',
 'examide',
 'citoglipton',
 'insulin',
 'glyburide-metformin',
 'glipizide-metformin',
 'glimepiride-pioglitazone',
 'metformin-rosiglitazone',
 'metformin-pioglitazone',
 'change',
 'diabetesMed',
 'readmitted']

In [7]:
df .dtypes

encounter_id                 int64
patient_nbr                  int64
race                        object
gender                      object
age                         object
weight                      object
admission_type_id            int64
discharge_disposition_id     int64
admission_source_id          int64
time_in_hospital             int64
payer_code                  object
medical_specialty           object
num_lab_procedures           int64
num_procedures               int64
num_medications              int64
number_outpatient            int64
number_emergency             int64
number_inpatient             int64
diag_1                      object
diag_2                      object
diag_3                      object
number_diagnoses             int64
max_glu_serum               object
A1Cresult                   object
metformin                   object
repaglinide                 object
nateglinide                 object
chlorpropamide              object
glimepiride                 object
acetohexamide               object
glipizide                   object
glyburide                   object
tolbutamide                 object
pioglitazone                object
rosiglitazone               object
acarbose                    object
miglitol                    object
troglitazone                object
tolazamide                  object
examide                     object
citoglipton                 object
insulin                     object
glyburide-metformin         object
glipizide-metformin         object
glimepiride-pioglitazone    object
metformin-rosiglitazone     object
metformin-pioglitazone      object
change                      object
diabetesMed                 object
readmitted                  object
dtype: object

In [9]:
df.isna().sum()

encounter_id                    0
patient_nbr                     0
race                            0
gender                          0
age                             0
weight                          0
admission_type_id               0
discharge_disposition_id        0
admission_source_id             0
time_in_hospital                0
payer_code                      0
medical_specialty               0
num_lab_procedures              0
num_procedures                  0
num_medications                 0
number_outpatient               0
number_emergency                0
number_inpatient                0
diag_1                          0
diag_2                          0
diag_3                          0
number_diagnoses                0
max_glu_serum               96420
A1Cresult                   84748
metformin                       0
repaglinide                     0
nateglinide                     0
chlorpropamide                  0
glimepiride                     0
acetohexamide                   0
glipizide                       0
glyburide                       0
tolbutamide                     0
pioglitazone                    0
rosiglitazone                   0
acarbose                        0
miglitol                        0
troglitazone                    0
tolazamide                      0
examide                         0
citoglipton                     0
insulin                         0
glyburide-metformin             0
glipizide-metformin             0
glimepiride-pioglitazone        0
metformin-rosiglitazone         0
metformin-pioglitazone          0
change                          0
diabetesMed                     0
readmitted                      0
dtype: int64

In [10]:
df.describe()

,encounter_id,patient_nbr,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,number_diagnoses
count,1.017660e+05,1.017660e+05,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000
mean,1.652016e+08,5.433040e+07,2.024006,3.715642,5.754437,4.395987,43.095641,1.339730,16.021844,0.369357,0.197836,0.635566,7.422607
std,1.026403e+08,3.869636e+07,1.445403,5.280166,4.064081,2.985108,19.674362,1.705807,8.127566,1.267265,0.930472,1.262863,1.933600
min,1.252200e+04,1.350000e+02,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000
25%,8.496119e+07,2.341322e+07,1.000000,1.000000,1.000000,2.000000,31.000000,0.000000,10.000000,0.000000,0.000000,0.000000,6.000000
50%,1.523890e+08,4.550514e+07,1.000000,1.000000,7.000000,4.000000,44.000000,1.000000,15.000000,0.000000,0.000000,0.000000,8.000000
75%,2.302709e+08,8.754595e+07,3.000000,4.000000,7.000000,6.000000,57.000000,2.000000,20.000000,0.000000,0.000000,1.000000,9.000000
max,4.438672e+08,1.895026e+08,8.000000,28.000000,25.000000,14.000000,132.000000,6.000000,81.000000,42.000000,76.000000,21.000000,16.000000

In [11]:
df['readmitted'].value_counts()

readmitted
NO     54864
>30    35545
<30    11357
Name: count, dtype: int64

In [12]:
for col in df.columns:
    unique_vals = df[col].unique()
    if '?' in unique_vals:
        print(f"{col}: {df[col].value_counts()['?']} question marks")

race: 2273 question marks
weight: 98569 question marks
payer_code: 40256 question marks
medical_specialty: 49949 question marks
diag_1: 21 question marks
diag_2: 358 question marks
diag_3: 1423 question marks

In [13]:
df.sample(20)

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
69714,198670974,107210547,AfricanAmerican,Female,[70-80),?,1,1,7,4,...,No,Down,No,No,No,No,No,Ch,Yes,>30
74385,221483982,108696717,Caucasian,Male,[70-80),?,1,6,7,6,...,No,No,No,No,No,No,No,No,Yes,>30
64318,179011116,86011983,Caucasian,Male,[70-80),?,1,3,7,12,...,No,No,No,No,No,No,No,No,Yes,<30
17855,65214810,91588428,Caucasian,Male,[60-70),?,2,2,4,2,...,No,No,No,No,No,No,No,No,Yes,<30
79685,244839756,92292228,Caucasian,Male,[70-80),?,2,3,7,13,...,No,Up,No,No,No,No,No,Ch,Yes,NO
70397,201876684,107096616,Caucasian,Female,[50-60),?,1,1,7,2,...,No,Steady,No,No,No,No,No,Ch,Yes,>30
23971,81601758,86632875,Caucasian,Female,[10-20),?,1,1,7,1,...,No,Up,No,No,No,No,No,Ch,Yes,NO
23514,80302818,10494018,Caucasian,Male,[80-90),?,1,3,7,2,...,No,No,No,No,No,No,No,No,Yes,NO
66647,186400728,93682980,Caucasian,Female,[20-30),?,1,1,7,4,...,No,No,No,No,No,No,No,No,No,NO
13078,52476996,447453,AfricanAmerican,Female,[60-70),?,1,1,7,5,...,No,Down,No,No,No,No,No,Ch,Yes,NO
36210,111511212,23465232,Caucasian,Female,[90-100),?,5,3,17,2,...,No,No,No,No,No,No,No,No,No,NO
39413,122675628,107114958,Caucasian,Female,[60-70),?,1,1,7,4,...,No,Steady,No,No,No,No,No,No,Yes,NO
9652,41762682,80798679,AfricanAmerican,Female,[50-60),?,1,1,7,1,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
65780,183681822,68376780,Hispanic,Male,[50-60),?,1,1,7,3,...,No,No,No,No,No,No,No,No,No,>30
97961,394903868,180854285,Caucasian,Male,[70-80),?,2,3,4,1,...,No,Down,No,No,No,No,No,Ch,Yes,NO
72659,213158442,90389691,Caucasian,Female,[60-70),?,2,1,1,4,...,No,Up,No,No,No,No,No,Ch,Yes,>30
81292,251633490,114109803,Caucasian,Female,[70-80),?,1,1,7,3,...,No,Steady,No,No,No,No,No,Ch,Yes,>30
97412,388430258,38707686,AfricanAmerican,Female,[50-60),?,1,1,7,3,...,No,No,No,No,No,No,No,No,Yes,NO
78083,237936756,42679134,Caucasian,Male,[70-80),?,3,1,1,1,...,No,No,No,No,No,No,No,No,No,>30
7307,34821984,1551996,Caucasian,Female,[50-60),?,1,1,7,3,...,No,Steady,No,No,No,No,No,Ch,Yes,NO

In [14]:
# For every column, show unique values
for col in df.columns:
    print(f"\n{col}: {df[col].unique()[:10]}")  # first 10 unique values

encounter_id: [2278392  149190   64410  500364   16680   35754   55842   63768   12522
   15738]

patient_nbr: [  8222157  55629189  86047875  82442376  42519267  82637451  84259809
 114882984  48330783  63555939]

race: ['Caucasian' 'AfricanAmerican' '?' 'Other' 'Asian' 'Hispanic']

gender: ['Female' 'Male' 'Unknown/Invalid']

age: ['[0-10)' '[10-20)' '[20-30)' '[30-40)' '[40-50)' '[50-60)' '[60-70)'
 '[70-80)' '[80-90)' '[90-100)']

weight: ['?' '[75-100)' '[50-75)' '[0-25)' '[100-125)' '[25-50)' '[125-150)'
 '[175-200)' '[150-175)' '>200']

admission_type_id: [6 1 2 3 4 5 8 7]

discharge_disposition_id: [25  1  3  6  2  5 11  7 10  4]

admission_source_id: [ 1  7  2  4  5  6 20  3 17  8]

time_in_hospital: [ 1  3  2  4  5 13 12  9  7 10]

payer_code: ['?' 'MC' 'MD' 'HM' 'UN' 'BC' 'SP' 'CP' 'SI' 'DM']

medical_specialty: ['Pediatrics-Endocrinology' '?' 'InternalMedicine'
 'Family/GeneralPractice' 'Cardiology' 'Surgery-General' 'Orthopedics'
 'Gastroenterology' 'Surgery-Cardiovascular/Thoracic' 'Nephrology']

num_lab_procedures: [41 59 11 44 51 31 70 73 68 33]

num_procedures: [0 5 1 6 2 3 4]

num_medications: [ 1 18 13 16  8 21 12 28 17 11]

number_outpatient: [ 0  2  1  5  7  9  3  8  4 12]

number_emergency: [0 1 2 4 3 9 5 7 6 8]

number_inpatient: [0 1 2 3 6 5 4 7 8 9]

diag_1: ['250.83' '276' '648' '8' '197' '414' '428' '398' '434' '250.7']

diag_2: ['?' '250.01' '250' '250.43' '157' '411' '492' '427' '198' '403']

diag_3: ['?' '255' 'V27' '403' '250' 'V45' '38' '486' '996' '197']

number_diagnoses: [ 1  9  6  7  5  8  3  4  2 16]

max_glu_serum: [nan '>300' 'Norm' '>200']

A1Cresult: [nan '>7' '>8' 'Norm']

metformin: ['No' 'Steady' 'Up' 'Down']

repaglinide: ['No' 'Up' 'Steady' 'Down']

nateglinide: ['No' 'Steady' 'Down' 'Up']

chlorpropamide: ['No' 'Steady' 'Down' 'Up']

glimepiride: ['No' 'Steady' 'Down' 'Up']

acetohexamide: ['No' 'Steady']

glipizide: ['No' 'Steady' 'Up' 'Down']

glyburide: ['No' 'Steady' 'Up' 'Down']

tolbutamide: ['No' 'Steady']

pioglitazone: ['No' 'Steady' 'Up' 'Down']

rosiglitazone: ['No' 'Steady' 'Up' 'Down']

acarbose: ['No' 'Steady' 'Up' 'Down']

miglitol: ['No' 'Steady' 'Down' 'Up']

troglitazone: ['No' 'Steady']

tolazamide: ['No' 'Steady' 'Up']

examide: ['No']

citoglipton: ['No']

insulin: ['No' 'Up' 'Steady' 'Down']

glyburide-metformin: ['No' 'Steady' 'Down' 'Up']

glipizide-metformin: ['No' 'Steady']

glimepiride-pioglitazone: ['No' 'Steady']

metformin-rosiglitazone: ['No' 'Steady']

metformin-pioglitazone: ['No' 'Steady']

change: ['No' 'Ch']

diabetesMed: ['No' 'Yes']

readmitted: ['NO' '>30' '<30']

In [15]:
# Only for categorical/string columns
for col in df.select_dtypes(include='object').columns:
    print(f"\n{col}:")
    print(df[col].value_counts())

race:
race
Caucasian          76099
AfricanAmerican    19210
?                   2273
Hispanic            2037
Other               1506
Asian                641
Name: count, dtype: int64

gender:
gender
Female             54708
Male               47055
Unknown/Invalid        3
Name: count, dtype: int64

age:
age
[70-80)     26068
[60-70)     22483
[50-60)     17256
[80-90)     17197
[40-50)      9685
[30-40)      3775
[90-100)     2793
[20-30)      1657
[10-20)       691
[0-10)        161
Name: count, dtype: int64

weight:
weight
?            98569
[75-100)      1336
[50-75)        897
[100-125)      625
[125-150)      145
[25-50)         97
[0-25)          48
[150-175)       35
[175-200)       11
>200             3
Name: count, dtype: int64

payer_code:
payer_code
?     40256
MC    32439
HM     6274
SP     5007
BC     4655
MD     3532
CP     2533
UN     2448
CM     1937
OG     1033
PO      592
DM      549
CH      146
WC      135
OT       95
MP       79
SI       55
FR        1
Name: count, dtype: int64

medical_specialty:
medical_specialty
?                                49949
InternalMedicine                 14635
Emergency/Trauma                  7565
Family/GeneralPractice            7440
Cardiology                        5352
                                 ...
SportsMedicine                       1
Speech                               1
Perinatology                         1
Neurophysiology                      1
Pediatrics-InfectiousDiseases        1
Name: count, Length: 73, dtype: int64

diag_1:
diag_1
428    6862
414    6581
786    4016
410    3614
486    3508
       ...
373       1
314       1
684       1
217       1
V51       1
Name: count, Length: 717, dtype: int64

diag_2:
diag_2
276     6752
428     6662
250     6071
427     5036
401     3736
        ...
E918       1
46         1
V13        1
E850       1
927        1
Name: count, Length: 749, dtype: int64

diag_3:
diag_3
250     11555
401      8289
276      5175
428      4577
427      3955
        ...
657         1
684         1
603         1
E826        1
971         1
Name: count, Length: 790, dtype: int64

max_glu_serum:
max_glu_serum
Norm    2597
>200    1485
>300    1264
Name: count, dtype: int64

A1Cresult:
A1Cresult
>8      8216
Norm    4990
>7      3812
Name: count, dtype: int64

metformin:
metformin
No        81778
Steady    18346
Up         1067
Down        575
Name: count, dtype: int64

repaglinide:
repaglinide
No        100227
Steady      1384
Up           110
Down          45
Name: count, dtype: int64

nateglinide:
nateglinide
No        101063
Steady       668
Up            24
Down          11
Name: count, dtype: int64

chlorpropamide:
chlorpropamide
No        101680
Steady        79
Up             6
Down           1
Name: count, dtype: int64

glimepiride:
glimepiride
No        96575
Steady     4670
Up          327
Down        194
Name: count, dtype: int64

acetohexamide:
acetohexamide
No        101765
Steady         1
Name: count, dtype: int64

glipizide:
glipizide
No        89080
Steady    11356
Up          770
Down        560
Name: count, dtype: int64

glyburide:
glyburide
No        91116
Steady     9274
Up          812
Down        564
Name: count, dtype: int64

tolbutamide:
tolbutamide
No        101743
Steady        23
Name: count, dtype: int64

pioglitazone:
pioglitazone
No        94438
Steady     6976
Up          234
Down        118
Name: count, dtype: int64

rosiglitazone:
rosiglitazone
No        95401
Steady     6100
Up          178
Down         87
Name: count, dtype: int64

acarbose:
acarbose
No        101458
Steady       295
Up            10
Down           3
Name: count, dtype: int64

miglitol:
miglitol
No        101728
Steady        31
Down           5
Up             2
Name: count, dtype: int64

troglitazone:
troglitazone
No        101763
Steady         3
Name: count, dtype: int64

tolazamide:
tolazamide
No        101727
Steady        38
Up             1
Name: count, dtype: int64

examide:
examide
No    101766
Name: count, dtype: int64

citoglipton:
citoglipton
No    101766
Name: count, dtype: int64

insulin:
insulin
No        47383
Steady    30849
Down      12218
Up        11316
Name: count, dtype: int64

glyburide-metformin:
glyburide-metformin
No        101060
Steady       692
Up             8
Down           6
Name: count, dtype: int64

glipizide-metformin:
glipizide-metformin
No        101753
Steady        13
Name: count, dtype: int64

glimepiride-pioglitazone:
glimepiride-pioglitazone
No        101765
Steady         1
Name: count, dtype: int64

metformin-rosiglitazone:
metformin-rosiglitazone
No        101764
Steady         2
Name: count, dtype: int64

metformin-pioglitazone:
metformin-pioglitazone
No        101765
Steady         1
Name: count, dtype: int64

change:
change
No    54755
Ch    47011
Name: count, dtype: int64

diabetesMed:
diabetesMed
Yes    78363
No     23403
Name: count, dtype: int64

readmitted:
readmitted
NO     54864
>30    35545
<30    11357
Name: count, dtype: int64

In [16]:
# Catches ALL common missing value disguises at once
missing_disguises = ['?', 'NA', 'N/A', 'na', 'n/a', 
                     'none', 'None', 'NONE', '-', 
                     '--', 'unknown', 'Unknown', ' ', '']

for col in df.columns:
    for disguise in missing_disguises:
        count = (df[col] == disguise).sum()
        if count > 0:
            print(f"{col} → '{disguise}' appears {count} times")

race → '?' appears 2273 times
weight → '?' appears 98569 times
payer_code → '?' appears 40256 times
medical_specialty → '?' appears 49949 times
diag_1 → '?' appears 21 times
diag_2 → '?' appears 358 times
diag_3 → '?' appears 1423 times

In [18]:
# Values that look empty but aren't
for col in df.select_dtypes(include='object').columns:
    whitespace = df[col].str.strip().eq('').sum()
    if whitespace > 0:
        print(f"{col} has {whitespace} whitespace-only values")

In [19]:
# Columns which are not useful for ML

print(df['encounter_id'].nunique())
print(df['patient_nbr'].nunique())

101766
71518

In [ ]:
# Checking columns which has only one unique value
for col in df.columns:
    if df[col].nunique() == 1:
        print(f"{col} has only 1 unique value → useless for ML")

examide has only 1 unique value → useless for ML
citoglipton has only 1 unique value → useless for ML

In [21]:
print(df['readmitted'].value_counts())
print("\nPercentage:")
print(df['readmitted'].value_counts(normalize=True) * 100)

readmitted
NO     54864
>30    35545
<30    11357
Name: count, dtype: int64

Percentage:
readmitted
NO     53.911916
>30    34.928169
<30    11.159916
Name: proportion, dtype: float64

# Cleaning the data

In [22]:
# Columns to drop

cols_to_drop = [
    'encounter_id',    # ID column
    'patient_nbr',     # ID column
    'examide',         # Zero variance
    'citoglipton',     # Zero variance
    'weight',          # 96.8% missing
    'payer_code',      # 39.6% missing
    'medical_specialty' # 49.1% missing
]

df.drop(columns=cols_to_drop, inplace=True)
print("Remaining columns:", df.shape[1])

Remaining columns: 43

In [ ]:
# Impute missing values with mode

cols_to_impute = ['race', 'diag_1', 'diag_2', 'diag_3']

for col in cols_to_impute:
    mode_value = df[col].mode()[0]
    df[col] = df[col].fillna(mode_value)

print("Missing values remaining:")
print(df.isnull().sum().sum())

Missing values remaining:
181168

In [24]:
# Convert target to binary

df['readmitted'] = (df['readmitted'] == '<30').astype(int)

print("Target distribution after conversion:")
print(df['readmitted'].value_counts())

Target distribution after conversion:
readmitted
0    90409
1    11357
Name: count, dtype: int64

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101766 entries, 0 to 101765
Data columns (total 43 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   race                      101766 non-null  object
 1   gender                    101766 non-null  object
 2   age                       101766 non-null  object
 3   admission_type_id         101766 non-null  int64
 4   discharge_disposition_id  101766 non-null  int64
 5   admission_source_id       101766 non-null  int64
 6   time_in_hospital          101766 non-null  int64
 7   num_lab_procedures        101766 non-null  int64
 8   num_procedures            101766 non-null  int64
 9   num_medications           101766 non-null  int64
 10  number_outpatient         101766 non-null  int64
 11  number_emergency          101766 non-null  int64
 12  number_inpatient          101766 non-null  int64
 13  diag_1                    101766 non-null  object
 14  diag_2                    101766 non-null  object
 15  diag_3                    101766 non-null  object
 16  number_diagnoses          101766 non-null  int64
 17  max_glu_serum             5346 non-null    object
 18  A1Cresult                 17018 non-null   object
 19  metformin                 101766 non-null  object
 20  repaglinide               101766 non-null  object
 21  nateglinide               101766 non-null  object
 22  chlorpropamide            101766 non-null  object
 23  glimepiride               101766 non-null  object
 24  acetohexamide             101766 non-null  object
 25  glipizide                 101766 non-null  object
 26  glyburide                 101766 non-null  object
 27  tolbutamide               101766 non-null  object
 28  pioglitazone              101766 non-null  object
 29  rosiglitazone             101766 non-null  object
 30  acarbose                  101766 non-null  object
 31  miglitol                  101766 non-null  object
 32  troglitazone              101766 non-null  object
 33  tolazamide                101766 non-null  object
 34  insulin                   101766 non-null  object
 35  glyburide-metformin       101766 non-null  object
 36  glipizide-metformin       101766 non-null  object
 37  glimepiride-pioglitazone  101766 non-null  object
 38  metformin-rosiglitazone   101766 non-null  object
 39  metformin-pioglitazone    101766 non-null  object
 40  change                    101766 non-null  object
 41  diabetesMed               101766 non-null  object
 42  readmitted                101766 non-null  int64
dtypes: int64(12), object(31)
memory usage: 33.4+ MB

In [ ]:
# Restore "None" as a valid category for test result columns
df['max_glu_serum'] = df['max_glu_serum'].fillna('None')
df['A1Cresult'] = df['A1Cresult'].fillna('None')

# Verify no missing values remain
print("Missing values remaining:")
print(df.isnull().sum().sum())

Missing values remaining:
0

In [30]:
# Final Check

print("Dataset Shape:", df.shape)
print("\nMissing Values:", df.isnull().sum().sum())
print("\nTarget Distribution:")
print(df['readmitted'].value_counts())

Dataset Shape: (101766, 43)

Missing Values: 0

Target Distribution:
readmitted
0    90409
1    11357
Name: count, dtype: int64

In [31]:
# Save cleaned data to processed folder

df.to_csv('../data/processed/cleaned_data.csv', index=False)
print("Cleaned data saved successfully!")

Cleaned data saved successfully!

In [ ]:
git